/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAsideMenu: typeof import('./src/components/layout/AppAsideMenu.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    Button: typeof import('primevue/button')['default']
    Form: typeof import('@primevue/forms/form')['default']
    PageTitle: typeof import('./src/components/page/PageTitle.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    PETable: typeof import('./src/components/table/PETable.vue')['default']
    PlatformLayout: typeof import('./src/components/layout/PlatformLayout.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/page/SearchFilter.vue')['default']
  }
}
